In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [76]:
class HebianNet():
    def __init__(self):
        self.weights = None
        self.trained = False
        
    def train(self,data):
        if not self.trained:
            self.weights = np.zeros((data.shape[1], data.shape[1]))
        for index in range(data.shape[0]):
            self.weights = np.add(np.outer(np.transpose(data[index,:]),data[index,:]),self.weights)
        self.trained = True
        
    def update(self, x):
        new = np.dot(x,self.weights)
        new[new>=0] = 1
        new[new<0] = -1
        return new
    
    def converge(self, x):
        error = 1
        itercount = 0
        while error > 0:
            new = self.update(x)
            error = sum(abs(new-x))
            x = new.copy()
            itercount += 1
        return x, itercount

### Hopfield network recall

In [77]:
x1 = np.array([-1,-1,1,-1,1,-1,-1,1])
x2 = np.array([-1,-1,-1,-1,-1,1,-1,-1])
x3 = np.array([-1,1,1,-1,-1,1,-1,1])
data  = np.array([x1,x2,x3])

In [78]:
hn = HebianNet()

In [79]:
hn.train(data)

Reproduces learned patterns

In [80]:
hn.update(x1)-x1

array([0., 0., 0., 0., 0., 0., 0., 0.])

### Convergence and attractors

In [81]:
x1d = np.array([1,-1,1,-1,1,-1,-1,1])
x2d = np.array([1,1,-1,-1,-1,1,-1,-1])
x3d = np.array([1,1,1,-1,1,1,-1,1])

In [82]:
hn.converge(x1d)[0]- x1

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [83]:
hn.converge(x2d)[0] - x2

array([0., 2., 0., 0., 0., 0., 0., 0.])

In [84]:
hn.converge(x3d)[0] - x3

array([0., 0., 0., 0., 0., 0., 0., 0.])

Only x1d and x3d converge towards their respective undistorted patterns. x2d does not.

In [85]:
searchgrid = np.ones((256,8))

In [86]:
searchgrid

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

#### More than half wrong

In [88]:
x1dd = np.multiply(x1,np.array([-1,-1,-1,-1,-1,1,1,1]))

In [89]:
new, iterations = hn.converge(x1dd)
new = np.multiply(new,x1).copy()
result = len(new[new<0])
print("Diff from original vector in {} elements. Number of iterations to convergance was {}".format(result,iterations))

Diff from original vector in 4 elements. Number of iterations to convergance was 3


In [90]:
hn.converge(x1dd)

(array([ 1.,  1.,  1.,  1.,  1., -1.,  1.,  1.]), 3)

In [91]:
x1

array([-1, -1,  1, -1,  1, -1, -1,  1])